sudo: required

services:
  - docker

language: python

install:
  # Install Ansible.
  - pip install ansible
  - pip install ansible-lint

script:
  # Check the role/playbook's syntax.
  - ansible-playbook playbook.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - test [ $DEBUG == $(true) ] && ansible-playbook playbook.yml -vvvv || ansible-playbook playbook.yml
